# sample Docker image with ONVAULT installed
FROM ubuntu:14.04

# installs Dockito Vault ONVAULT utility
# https://github.com/dockito/vault
ADD https://raw.githubusercontent.com/dockito/vault/master/ONVAULT /usr/local/bin/ONVAULT
RUN chmod +x /usr/local/bin/ONVAULT
